module.exports = {
    messages: [
        "bat naiinis aso ko", "luh naiinis to a", "luh bat ka naiinis", "naiinis ka ah", "naiinis ka", "asar to", "e naiinis na to", "wala iyakan", "e bat ka naiyak", "iyakin ah", "luhh umiyak", "bat ka naiyak", "ay grabe", "weh", "huh", "luhh", "luh", "ano raw", "sinabi koyan", "dog ka e", "aso ka e", "tutal aso kita", "e nag inaso asoko", "bat nag iinaso to", "asohan mopa", "doggie?", "pst doggie", "aso kanga", "aso kita hoy", "sml molang", "share molang", "sml?", "e nag sml", "sml nga", "sml molang", "sml", "kwento mo", "natawa lolako", "dog ko to", "dog ko to ah", "de dog kita", "dog to", "aso to", "dog to", "e aso kita", "de aso ka", "e aso nga kita", "aso ko nga pala", "md mo", "post mo", "asan", "san", "sino", "asan ba", "asan nga", "asan pakeko", "di nga", "weh", "talaga?", "ngek", "luh pakeko", "pagod na asoko ah", "wag ka mapagod aso",
        "😡", "😤", "🤬", "😠", "😾", "👿", "😒", "😖", "😣", "😩", "😫", "🥵", "😵", "😵‍💫", "😕", "🙃", "😑", "😶", "😧", "😨", "😰", "😥", "😓", "😱", "😮‍💨", "🤯", "😬", "😳", "🥴",
        "asar ka dog", "e asar to dogs ko", "dogskie ka", "wala mwawala?", "e feel ko pagod ka na", "pagod na to a", "wag moko ewan", "wala ewanan to", "aso pst", "psttt", "dog psttt", "duggie pst", "pst pst", "pst pstt!", "Haha pst!", "pst!", "dog!", "aso!",
        "luhhhh anorawww", "anoraww??", "ano", "sinasabe netong asong to", "wydm dog", "what dog",
        "cornyhan mo pa, utos ko", "corny mo jan", "corny ahh", "corny lods", "corny wala ba bago", "subra corny", "corny nyan", "e ang corny ng dog ko", "corny mo na aso ah", "bat ang corny ng aso ko", "asoko corny", "corny mo aso??",
        "o tapos", "ano pa", "tapos tapos", "tapos", "meron pa ba", "ano sunod", "ano", "next", "next joke", "corny mag joke", "joke yan", "joker to a", "joker to ah", "ay grabe magjoke", "lala mag joke", "lala angcorny", "corny neto", "joker to ah Haha",
        "edi aso kita", "e aso nanga kita", "bulldog", "ano breed mo aso", "hoy aso wala kakain", "gutom na dogsko ah", "muka gutom na asoko", "hoy gutom kanaba aso", "luh gutom nato", "wala iwanan to aso", "bat ka matutulog aso", "maaga pa para matulog ah", "hoy antok kana", "muka inaantok asoko", "bat ka inaantok doggie", "dogsko antok kana ah", "hoy aso sumabay ka", "di maka sabay doggieko", "aso wag kanga mawawala", "bagalan mopa", "dito lang tayo",
        "inis nako jan", "naiinis nako ah", "Bat naiinis nako", "Lt galit nako Haha", "e ikaw dog ko", "aso wag ka iiyak", "iyakin to ah lt", "hoy doggieko", "wag ka iiyak", "tolongges", "luh pagod ka na", "hoy aso wag ka mapagod", "nge wala iwanan to", "pst nawawala ka aso", "mukampagod asoko", "e askal ka", "hoy askal kanga", "sinasabe netong dog ko", "pakeko aso", "hoy wag ka mawawala", "tatamaan ka saken", "wala na corny na", "Hahah", "eh", "ulol",
        "tarantado", "proud siraulo asoko ah", "ah basta aso kita", "doggie dont cry", "iyak aso", "bat umiiyak to", "why kaya", "asuhin kita", "isa panga", "next juk", "ano sunod nyan", "may sunod pato?", "hoy ano nga sunod", "isa panga", "mag joke kapa", "joke more", "more joke pa", "e dinurog kita", "hoy aso bat ka saken durog", "durog asoko ah", "lugmok dogsko", "eh inaso kuto", "hoy muka kuto", "eh aso ka"
    ]
};
