module.exports = {
    messages: [
        "bat naiinis aso ko", "luh naiinis to a", "luh bat ka naiinis", "naiinis ka ah", "naiinis ka", "asar to", "e naiinis na to", "wala iyakan", "e bat ka naiyak", "iyakin ah", "luhh umiyak", "bat ka naiyak", "dog ko", "dog kita ahhh", "aso ka??", "aso ka", "aso ka na", "a s o ka", "a s o ka na", "aso kaaa", "aso ka na!", "aso ka…", "a-s-o ka", "aso ka na??", "a s o ka na!", "aso kaah", "aso ka naaa", "asoo ka", "aso ka naa", "a-s-o ka na", "aso kaahh", "a s o ka na?", "aso ka…!", "asooo ka na", "a-s-o kaah", "aso ka naah", "a s o ka…", "aso ka??", "aso kaah!", "a-s-o ka na…", "aso ka na!?!", "a s o kaah", "asoo ka na!", "aso ka…?", "a-s-o kaahh", "aso ka naa!", "aso ka!", "a s o ka…", "aso kaah??", "a-s-o ka naah", "aso ka na…", "a s o kaah!", "aso ka??!", "aso ka na…!", "a-s-o ka…", "aso kaah na", "a s o ka…!", "aso ka naa??", "aso kaah…", "a-s-o ka na!?", "aso ka naaa!", "a s o ka…?", "aso kaah na",
        "karasu doggie", "karaso aso", "e aso tong karashu", "luh e askal karasu", "mejo aso karasu ah", "aso nga karasu", "diba aso karashu", "aso tong karasu", "hoy karasu aso kita", "karashu dog-gie", "kar-aso", "asokonga pala karasu pangalan", "asokonga karasu", "oona asokokarasu", "", "doggie karasu", "aso karasu", "doggieng karasu", "karasu dogs", "pero asoko karasu", "de asoko karasu", "corny karasu ah", "asoo karaso", "asongkarasu", "dog karasu", "corny mo karasu dog", "asong karasu", "asoko karasu", "asokokarasu ab",
        "asar ka dog", "e asar to dogs ko", "dogskie ka", "wala mwawala?", "e feel ko pagod ka na", "pagod na to a", "wag moko ewan", "wala ewanan to", "aso pst", "psttt", "dog psttt", "duggie pst", "pst pst", "pst pstt!", "Haha pst!", "pst!", "dog!", "aso!",
        "luhhhh anorawww", "anoraww??", "ano", "sinasabe netong asong to", "wydm dog", "what dog",
        "cornyhan mo pa, utos ko", "corny mo jan", "corny ahh", "corny lods", "corny wala ba bago", "subra corny", "corny nyan", "e ang corny ng dog ko", "corny mo na aso ah", "bat ang corny ng aso ko", "asoko corny", "corny mo aso??",
        "o tapos", "ano pa", "tapos tapos", "tapos", "meron pa ba", "ano sunod", "ano", "next", "next joke", "corny mag joke", "joke yan", "joker to a", "joker to ah", "ay grabe magjoke", "lala mag joke", "lala angcorny", "corny neto", "joker to ah Haha",
        "inis nako jan", "naiinis nako ah", "Bat naiinis nako", "Lt galit nako Haha", "e ikaw dog ko"
    ]
};
